apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfojanitor-backend
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  accessPolicy:
    inbound:
      rules:
        - application: syfojanitor-frontend
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: syfojanitor-backend-db
        diskAutoresize: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: 05b6c0d2-b6db-4440-96b4-4de66c09b3c6 # teamsykefravr
  kafka:
    pool: nav-dev
  env:
    - name: KTOR_ENV
      value: "production"
